// SPDX-License-Identifier: AGPL-3.0-or-later
use std::fmt::Write;
use std::fs;

mod vector_format;

use af_field_ref::goldilocks::{add_mod, MODULUS as GOLDILOCKS};
use clap::Parser;
use serde_json::{json, to_string, to_string_pretty};
use vector_format::{VectorEntry, VectorMetadata, VectorSet};

type DynError = Box<dyn std::error::Error + Send + Sync + 'static>;

fn parse_hex_u64(value: &str) -> Result<u64, DynError> {
    let clean = value.trim_start_matches("0x");
    Ok(u64::from_str_radix(clean, 16)?)
}

fn u64_to_hex(value: u64) -> String {
    format!("0x{value:016X}")
}

fn fnv1a_hash64(input: &str) -> u64 {
    let mut hash: u64 = 14_695_981_039_346_656_037;
    for byte in input.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(1_099_511_628_211);
    }
    hash
}

fn metadata_digest(
    ip: &str,
    modulus: &str,
    seed: u64,
    count: usize,
    vectors: &[VectorEntry],
) -> Result<String, DynError> {
    let payload = json!({
        "ip": ip,
        "modulus": modulus,
        "seed": seed,
        "count": count,
        "vectors": vectors,
    });
    let encoded = to_string(&payload)?;
    Ok(format!("0x{:016X}", fnv1a_hash64(&encoded)))
}

#[derive(Debug, Parser)]
#[command(name = "af-vectors", version)]
struct Args {
    #[arg(long, default_value = "vectors/af_mod_add_basic.json")]
    basic_out: String,
    #[arg(long, default_value = "vectors/af_mod_add_random.json")]
    random_out: String,
    #[arg(long, default_value = "vectors/af_mod_add_random.svh")]
    svh_out: String,
    #[arg(long, default_value_t = 64)]
    count: usize,
    #[arg(long, default_value = "0x1234567890ABCDEF")]
    seed: String,
}

#[derive(Clone)]
struct XorShift64 {
    state: u64,
}

impl XorShift64 {
    fn new(seed: u64) -> Self {
        Self {
            state: seed.wrapping_add(0x9E3779B97F4A7C15),
        }
    }

    fn next_u64(&mut self) -> u64 {
        let mut x = self.state;
        x ^= x << 7;
        x ^= x >> 9;
        x ^= x << 8;
        self.state = x;
        self.state
    }
}

fn write_json(file: &str, data: &VectorSet) -> Result<(), DynError> {
    let mut json = to_string_pretty(data)?;
    json.push('\n');
    Ok(fs::write(file, json)?)
}

fn write_svh(file: &str, vectors: &[VectorEntry]) -> Result<(), DynError> {
    let mut out = String::new();
    out.push_str("// SPDX-License-Identifier: AGPL-3.0-or-later\n");
    out.push_str("// Auto-generated by af-vectors\n");
    out.push_str("`ifndef AF_MOD_ADD_RANDOM_SVH\n");
    out.push_str("`define AF_MOD_ADD_RANDOM_SVH\n");
    writeln!(
        out,
        "localparam int AF_MOD_ADD_RANDOM_COUNT = {};",
        vectors.len()
    )?;
    out.push_str(
        "localparam logic [63:0] AF_MOD_ADD_RANDOM_A [0:AF_MOD_ADD_RANDOM_COUNT-1] = '{\n",
    );
    for (idx, item) in vectors.iter().enumerate() {
        let sep = if idx + 1 == vectors.len() { "" } else { "," };
        writeln!(out, "    64'h{}{}", item.a.trim_start_matches("0x"), sep)?;
    }
    out.push_str("};\n\n");
    out.push_str(
        "localparam logic [63:0] AF_MOD_ADD_RANDOM_B [0:AF_MOD_ADD_RANDOM_COUNT-1] = '{\n",
    );
    for (idx, item) in vectors.iter().enumerate() {
        let sep = if idx + 1 == vectors.len() { "" } else { "," };
        writeln!(out, "    64'h{}{}", item.b.trim_start_matches("0x"), sep)?;
    }
    out.push_str("};\n\n");
    out.push_str(
        "localparam logic [63:0] AF_MOD_ADD_RANDOM_EXPECTED [0:AF_MOD_ADD_RANDOM_COUNT-1] = '{\n",
    );
    for (idx, item) in vectors.iter().enumerate() {
        let sep = if idx + 1 == vectors.len() { "" } else { "," };
        writeln!(
            out,
            "    64'h{}{}",
            item.expected.trim_start_matches("0x"),
            sep
        )?;
    }
    out.push_str("};\n`endif\n");
    Ok(fs::write(file, out)?)
}

fn main() -> Result<(), DynError> {
    let args = Args::parse();

    let basic = vec![
        VectorEntry {
            a: u64_to_hex(0),
            b: u64_to_hex(0),
            expected: u64_to_hex(add_mod(0, 0, GOLDILOCKS)),
        },
        VectorEntry {
            a: u64_to_hex(1),
            b: u64_to_hex(1),
            expected: u64_to_hex(add_mod(1, 1, GOLDILOCKS)),
        },
        VectorEntry {
            a: u64_to_hex(GOLDILOCKS - 1),
            b: u64_to_hex(1),
            expected: u64_to_hex(add_mod(GOLDILOCKS - 1, 1, GOLDILOCKS)),
        },
        VectorEntry {
            a: u64_to_hex(GOLDILOCKS - 1),
            b: u64_to_hex(GOLDILOCKS - 1),
            expected: u64_to_hex(add_mod(GOLDILOCKS - 1, GOLDILOCKS - 1, GOLDILOCKS)),
        },
    ];

    let seed = parse_hex_u64(&args.seed)?;
    let mut rng = XorShift64::new(seed);

    let mut random_vectors = Vec::with_capacity(args.count);
    for _ in 0..args.count {
        let a = rng.next_u64() % GOLDILOCKS;
        let b = rng.next_u64() % GOLDILOCKS;
        let expected = add_mod(a, b, GOLDILOCKS);
        random_vectors.push(VectorEntry {
            a: u64_to_hex(a),
            b: u64_to_hex(b),
            expected: u64_to_hex(expected),
        });
    }

    let basic_metadata_hash = metadata_digest(
        "af_mod_add",
        &u64_to_hex(GOLDILOCKS),
        seed,
        basic.len(),
        &basic,
    )?;

    let random_metadata_hash = metadata_digest(
        "af_mod_add",
        &u64_to_hex(GOLDILOCKS),
        seed,
        random_vectors.len(),
        &random_vectors,
    )?;

    let basic_set = VectorSet {
        metadata: VectorMetadata {
            ip: "af_mod_add".to_string(),
            modulus: u64_to_hex(GOLDILOCKS),
            seed,
            count: basic.len(),
            metadata_hash: basic_metadata_hash,
        },
        vectors: basic.clone(),
    };

    let random_set = VectorSet {
        metadata: VectorMetadata {
            ip: "af_mod_add".to_string(),
            modulus: u64_to_hex(GOLDILOCKS),
            seed,
            count: random_vectors.len(),
            metadata_hash: random_metadata_hash,
        },
        vectors: random_vectors.clone(),
    };

    write_json(&args.basic_out, &basic_set)?;
    write_json(&args.random_out, &random_set)?;
    write_svh(&args.svh_out, &random_vectors)?;

    println!(
        "generated {} basic vectors and {} random vectors",
        basic_set.vectors.len(),
        random_set.vectors.len()
    );
    Ok(())
}
